name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/workflows'
  pull_request:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ecs:
    name: ECS
    uses: craftcms/.github/.github/workflows/ecs.yml@v2
    with:
      php_version: '8.0'
  notify-slack:
    name: Notify Slack
    needs: [ecs]
    if: ${{ always() }}
    uses: craftcms/.github/.github/workflows/notify-slack.yml@v2
    with:
      success: ${{ needs.ecs.result == 'success' }}
      failure: ${{ needs.ecs.result == 'failure' }}
      failure_text_prefix: <!subteam^SGFL9NKNZ>
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_PLUGIN_WEBHOOK_URL }}
